### PR TITLE
Feature/location finder test

### PR DESCRIPTION
**Pull request by tiagobrunoBFR**
Tests finalized

### CODE REVIEW

**Comment by filhodanuvem** [comment]
Nice job! It's really similar with the answers branch 🎉 

https://github.com/filhodanuvem/treinando-unit-tests-php/blob/respostas/tests/LocationFinderTest.php

**Comment by tiagobrunoBFR** [comment]
> Nice job! It's really similar with the answers branch 
> 
> https://github.com/filhodanuvem/treinando-unit-tests-php/blob/respostas/tests/LocationFinderTest.php

Thank you, what books do you recommend to study php?

**Comment by filhodanuvem** [comment]
Honestly books about programming languages have a common problem of being quickly outdated. If you already know any programming language and would like to jump into php world, use the official documentation or even the site [https://phptherightway.com/](https://phptherightway.com/). They are good options.

**Comment by tiagobrunoBFR** [comment]
> Honestly books about programming languages have a common problem of being quickly outdated. If you already know any programming language and would like to jump into php world, use the official documentation or even the site https://phptherightway.com/. They are good options.

humm, thank you very much

**Pull request closed without merging**
